name: kn_fit_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.1
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  equatable: ^2.0.5

dev_dependencies: 
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

