// Mocks generated by Mockito 5.3.2 from annotations
// in kn_fit_app/test/app/features/student/data/repositories/student_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kn_fit_app/app/features/student/data/data/datasources/remote_data_source.dart'
    as _i3;
import 'package:kn_fit_app/app/features/student/data/data/models/student_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStudentModel_0 extends _i1.SmartFake implements _i2.StudentModel {
  _FakeStudentModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i3.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.StudentModel> getInfoStudent(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInfoStudent,
          [id],
        ),
        returnValue: _i4.Future<_i2.StudentModel>.value(_FakeStudentModel_0(
          this,
          Invocation.method(
            #getInfoStudent,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.StudentModel>);
}
